name = "AzSessions"
uuid = "f239b30d-ae6b-58be-a2d5-7e9f30e280a9"
version = "2.1.8"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONWebTokens = "9b8beb19-0777-58c6-920b-28f749fee4d3"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
Base64 = "1"
Dates = "1"
HTTP = "1"
JSON = "0.21"
JSONWebTokens = "0.2, 0.3, 1"
Logging = "1"
MbedTLS = "0.6.8, 0.7, 1"
Random = "1"
Sockets = "1"
julia = "1"
